# 1. Base image
FROM node:20-alpine

# 2. Set working directory inside container
WORKDIR /app

# 3. Copy dependency files first (for caching)
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy rest of the project
COPY . .

# 6. Expose port (same as your app)
EXPOSE 5173

# 7. Start the app
CMD ["npm", "run", "dev"]
